### PR TITLE
Hotfix load_qnnli in glue_utils.py

### PR DESCRIPTION
**Pull request by tommy19970714**
I receive two asset error on `prepro.py`. Specifically, it is in `glue_utils.py` called from `prepro.py`.
The errors are shown below. And I fixed the errors.

```
Traceback (most recent call last):
  File "prepro.py", line 352, in <module>
    main(args)
  File "prepro.py", line 193, in main
    qnnli_train_data = load_qnnli(qnli_train_path, GLOBAL_MAP['qnli'])
  File "./mt-dnn/data_utils/glue_utils.py", line 113, in load_qnnli
    assert len(lines) % 2 == 0
AssertionError
```

```
Traceback (most recent call last):
  File "prepro.py", line 352, in <module>
    main(args)
  File "prepro.py", line 195, in main
    qnnli_test_data = load_qnnli(qnli_test_path, GLOBAL_MAP['qnli'], is_train=False)
  File "./mt-dnn/data_utils/glue_utils.py", line 122, in load_qnnli
    assert block1[1] == block2[1]
AssertionError
```

### CODE REVIEW

**Comment by namisan** [comment]
@tommy19970714  load_qnnli is a function to handle old version of QNLI which we formulate it as a ranking task. A better solution is that we can add a flag indicating if we use the latest version or old version in prepro.py. Furthermore, it is an example of pairwise ranking for users. Wondering if could you help us fix this? thanks. Xiaodong

**Comment by devesh-tewari** [comment]
> @tommy19970714 load_qnnli is a function to handle old version of QNLI which we formulate it as a ranking task. A better solution is that we can add a flag indicating if we use the latest version or old version in prepro.py. Furthermore, it is an example of pairwise ranking for users. Wondering if could you help us fix this? thanks. Xiaodong

Whese can I find the old version of QNLI?

**Comment by namisan** [comment]
@devesh-tewari , You may need to contact with the GLUE team.

**Comment by devesh-tewari** [comment]
> @devesh-tewari , You may need to contact with the GLUE team.

Please just tell me what attributes did the old version of QNLI have?

**Comment by namisan** [comment]
@devesh-tewari The Old QNLI is arranged as pairs of positive/negative training/test samples. Thus, it is naturally formalized as a ranking task. However, in the latest version, they removed this pair informations.

**Comment by namisan** [comment]
Thanks everyone for help. I think the bugs have been fixed, and I'll close this pull request.

**Pull request closed without merging**
